# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Details.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import sqlite3 as sq

class Ui_Form(object):

    def queries(self):
        con = sq.connect('Inventory.db')
        q1 = 'SELECT O.ProductId as ProductId, P.Product_name as Product_name, count(O.OrderID) as No_Of_Orders, sum(O.profit) as Profit, P.Availability, P.rating FROM order_details O INNER Join product P ON O.ProductId = P.Product_ID GROUP BY O.ProductId;'
        r2 = pd.read_sql(q1, con)
        print(r2)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(6, 13, 381, 241))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 260, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.queries)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Details"))
        self.label.setText(_translate("Form", "Product Details:"))
        self.pushButton.setText(_translate("Form", "Visualize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
